name: mystore
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1


  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  google_sign_in : ^4.0.7
  provider: ^4.3.2+2
  font_awesome_flutter:
  flutter_masked_text: ^0.8.0

  google_fonts: ^1.1.1
  flutter_svg: ^0.19.2+1
  cloud_firestore:
  json_annotation: ^3.1.1
  shared_preferences: ^0.5.12+4

  #remove functionality
  geolocator:
  google_maps_flutter:
  flutter_cielo: 1.0.6

  #image_picker: ^0.6.7+22
  firebase_storage: ^5.2.0
  path_provider: ^1.6.27
  http: ^0.12.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^1.11.1
  json_serializable: ^3.5.1

  bloc_pattern:
  rxdart:

flutter:
  uses-material-design: true


  assets:
    # - assets/1.png
    # - assets/google.png
    # - assets/moto.png
    # - assets/map.png
    # - assets/foodtukk.png
    # - assets/foodtukk1.png
    - assets/































